language: rust
rust:
  - stable
os:
  - linux
  - osx
matrix:
  fast_finish: true
before_script:
  - rustup component add rustfmt-preview
  - rustup component add clippy-preview
script:
  - cargo fmt --all -- --check
  - cargo clippy --all -- -D clippy::pedantic
  - cargo build --release
  - chmod +x target/release/apk-decompiler
  - mkdir output
  - mv target/release/apk-decompiler output/apk-decompiler
  - mv lib output/lib
  # - gzip -k -f output
  - tar -zcvf apk-decompiler.tar.gz output/
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then mv apk-decompiler.tar.gz apk_decompiler_linux.tar.gz ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then mv apk-decompiler.tar.gz apk_decompiler_osx.tar.gz ; fi

deploy:
  provider: releases
  api_key: $gh_key
  file:
    - apk_decompiler_linux.tar.gz
    - apk_decompiler_osx.tar.gz
  skip_cleanup: true
  on:
    tags: true
